### ISSUE TITLE
Add .csv file of RIOs

### ISSUE THREAD

**Issue by alvinedrada** [uhm-gitclubs/uhm-gitclubs#17]
Please do work for this task in a branch named issue-17.

Add .csv file of RIOs with club data, providing data that adheres to the club schema

**Comment by leedenkraquel** [comment]
convert the csv to a json and load that json in through the 'assets' mechanism within meteor

**Comment by leedenkraquel** [comment]
when the system starts up, the app should load from a private directory through the assets mechanism
