### ISSUE TITLE
Search and Filter for browsing/home page

### ISSUE THREAD

**Issue by yongu2000** [uhm-gitclubs/uhm-gitclubs#21]
Show the clubs that are only searched.

Filter by
tags, most members

**Comment by alvinedrada** [comment]
Implemented a search bar on the browse clubs page. Users are able to search by club names or tags. Needs more research on how to implement a filter by tags or most members. 
![image](https://user-images.githubusercontent.com/77649183/115699023-f6bf6d00-a300-11eb-9d47-aff17bc70a52.png)
![image](https://user-images.githubusercontent.com/77649183/115699102-0d65c400-a301-11eb-86d8-9298ebf39993.png)
