### ISSUE TITLE
Make club label 'x' function as intended

### ISSUE THREAD

**Issue by CrisJavier** [uhm-gitclubs/uhm-gitclubs#29]
Please do work for this task in a branch named issue-29-delete-label-functionality.

Merge this branch with the M2 branch or the issue-23 branch.

Currently, it's set such that in the manage clubs (admin) page, the delete club label 'x' hides just label 1. None of the other 'x's work.

**Comment by leedenkraquel** [comment]
when you click the 'x' button on the tag. It removes that tag from that club's tag array in the database
