### ISSUE TITLE
Implement acceptance testing

### ISSUE THREAD

**Issue by alvinedrada** [uhm-gitclubs/uhm-gitclubs#42]
Please do work for this task in a branch named issue-42.

All testcafe-tests test for site/page functionality and all tests pass.

**Comment by leedenkraquel** [comment]
Testcafe tests:
1) landing page 
2) signin & signout
3) join club as john@foo.com
4) leave club as john@foo.com
5) join club as admin@foo.com
6) edit club as admin@foo.com
7) leave club as admin@foo.com

**Comment by leedenkraquel** [comment]
8. create club as admin@foo.com
